target: fix wrap-based subproject download in bitbake
Bitbake disables automatic wrap-based downloads, which caused the
build to fail with:

  ERROR: Automatic wrap-based subproject downloading is disabled

Updated the meson build to remove reliance on wrap downloads and
use proper system/Yocto-provided dependencies instead.

Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: Icf7b9e4824b556f8f09b22e4ac460e6517fbcd90